image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - package
  - deploy

pages:
  image: mhart/alpine-node:11
  stage: build
  script: 
   - yarn install
   - yarn test
   - yarn build
   - mv build public
  artifacts:
    paths:
      - public
#  rules:
#    - if: $CI_COMMIT_TAG


docker-build:
  stage: package
  script:
   - docker build -t registry.gitlab.com/toofun-group/kaseb-web-client .
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
   - docker push registry.gitlab.com/toofun-group/kaseb-web-client
  rules:
    - if: $CI_COMMIT_TAG

#arvan-deploy:
#  image: mormoroth/arvancli
#  stage: deploy
#  script:
#  - echo "$ARVAN_CLI_TOKEN\n" | arvan login
#  - arvan paas status
#  - gcloud auth activate-service-account --key-file key.json
#  - gcloud config set compute/zone europe-west1-c
#  - gcloud config set project actuator-sample
#  - gcloud config set container/use_client_certificate True
#  - gcloud container clusters get-credentials actuator-sample
#  - kubectl delete secret registry.gitlab.com
#  - kubectl create secret docker-registry registry.gitlab.com --docker-server=https://registry.gitlab.com --docker-username=marcolenzo --docker-password=$REGISTRY_PASSWD --docker-email=lenzo.marco@gmail.com
#  - kubectl apply -f deployment.yml
#  rules:
#    - if: $CI_COMMIT_TAG
