image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
   - node_modules/
    
stages:
  - build
  - package
  - deploy

uarn-build:
  image: mhart/alpine-node:11
  stage: build
  script:
   - yarn install
   - yarn test
   - CI=false yarn build
  artifacts:
    paths:
      - build
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'


docker-build:
  stage: package
  script:
   - docker build -t registry.gitlab.com/toofun-group/kaseb-web-client .
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
   - docker push registry.gitlab.com/toofun-group/kaseb-web-client
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'

nl-deploy:
  stage: deploy
  script:
    - whoami
    - sudo docker-compose -f /docker-compose.yml pull client
    - sudo docker-compose -f /docker-compose.yml up -d
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'
  tags:
    - nl1
